DROP VIEW IF EXISTS Bids_100;
CREATE VIEW Bids_100 AS
SELECT ItemID, Amount FROM Bids WHERE CAST(Bids.Amount AS NUMBER)>100;

SELECT COUNT(DISTINCT C.Cat)
FROM Categories C
JOIN Bids_100 ON C.ItemID = Bids_100.ItemID
